enable_modelarts: 0

device_target: 'Ascend'
device_id: 0

# Url for modelarts
data_url: ""
train_url: ""
checkpoint_url: ""
output_path: "/cache/train"

file_name: 'soft_tiny.mindir'
file_format: 'MINDIR'

backbone: 'soft_tiny'
train_image_size: 224
class_num: 1000
batch_size: 1
soft_config_path: 'models.softmax_free_vision_transformer.SOFTConfig'

# load model
pretrained: './soft_tiny.ckpt'
